version: '3'
services:
  app:
    container_name: pedido_app_container
    build: .
    ports:
      - "7740:7740"
    networks:
      - entregamaisnetwork
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: pedido_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ifpb
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres
    volumes:
      - pedido-postgres-data:/data/postgres
    ports:
      - "7741:5432"
    networks:
      - entregamaisnetwork
    restart: unless-stopped

  redis:
    container_name: pedido_redis_container
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: pedido_redis-commander_container
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "7749:8081"

networks:
  entregamaisnetwork:
    name: entregamaisnetwork

volumes:
  pedido-postgres-data:
  # pacote-pgadmin-data: