version: '3'
services:
  app:
    container_name: pedido_app_container
    build: .
    volumes:
      - pedido-app-data:/app
    ports:
      - "7740:7740"
    networks:
      - entregamaisnetwork
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: pedido_postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ifpb
      POSTGRES_PASSWORD: ifpb
      PGDATA: /data/postgres
    volumes:
      - pedido-postgres-data:/data/postgres
      - pedido-postgres-db-data:/var/lib/postgresql/data
    ports:
      - "7741:5432"
    networks:
      - entregamaisnetwork
    restart: unless-stopped

  redis:
    container_name: pedido_redis_container
    hostname: redis.pedido
    image: redis
    volumes: 
      - pedido-redis-data:/data
    ports:
      - "7748:6379"

  redis-commander:
    container_name: pedido_redis-commander_container
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis.pedido:6379
    ports:
      - "7749:8081"

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ifpb@ifpb.edu.br
  #     PGADMIN_DEFAULT_PASSWORD: ifpb
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "7000:80"
  #   networks:
  #     - entregamaisnetwork
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

networks:
  entregamaisnetwork:
    name: entregamaisnetwork

volumes:
  pedido-app-data:
  pedido-postgres-data:
  pedido-postgres-db-data:
  pedido-redis-data:

  # pacote-pgadmin-data: